version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:9.0.3
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: ovp-admin
      KEYCLOAK_PASSWORD: ovp-admin