---

apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: ovp-server
metadata:
  name: ovp-server
  annotations:
    openshift.io/display-name: OVP Starter 
    description: |-
        This template allows for the deployment of the Open Volunteer Platform application.
        The OVP app contains an example Node.js server implementation that 
        connects to a MongoDB database.
        For more information, see http://openvolunteer.org/
    tags: sync, mobile, nodejs
    iconClass: icon-nodejs
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/documentation-url: https://access.redhat.com/documentation/en-us/red_hat_managed_integration/1/html-single/developing_a_data_sync_app/index
    openshift.io/support-url: https://access.redhat.com
    template.openshift.io/bindable: 'false'
    aerogear.org/datasync-template-version: '0.9.3' # TODO needs changing?
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: open-volunteer-platform
    name: ovp-server
  spec:
    replicas: 1
    selector:
      app: open-volunteer-platform
      deploymentconfig: ovp-server
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: open-volunteer-platform
          deploymentconfig: ovp-server
      spec:
        volumes:
          - name: keycloak-server
            configMap:
              name: keycloak-config
              items:
              - key: "server"
                path: "keycloak.json"
          - name: keycloak-client
            configMap:
              name: keycloak-config
              items:
              - key: "client"
                path: "keycloak.json"         
        containers:
        - env:
            - name: MONGO_HOST
              value: mongodb
            - name: MONGO_USER
              value: user
            - name: MONGO_PASSWORD
              value: password
            - name: KAFKA_HOST
              value: kafka
            - name: KAFKA_PORT
              value: "9092" 
            - name: NODE_ENV
              value: development # To activate playground for demo   
          image: quay.io/graphql/ovp-debezium # TODO change image name
          name: ovp-server
          readinessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: 4000
            initialDelaySeconds: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: 4000
            initialDelaySeconds: 1
            timeoutSeconds: 1 
          ports:
          - containerPort: 4000
            protocol: TCP
          resources: {}
          volumeMounts:
            - name: keycloak-server
              mountPath: "/usr/src/app/config/keycloak.json"
              readOnly: false
              subPath: keycloak.json
            - name: keycloak-client
              mountPath: "/usr/src/admin/keycloak.json"
              subPath: keycloak.json
              readOnly: false   
    triggers:
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: open-volunteer-platform
    name: ovp-server
  spec:
    ports:
    - name: 4000-tcp
      port: 4000
      protocol: TCP
      targetPort: 4000
    selector:
      app: open-volunteer-platform
      deploymentconfig: ovp-server

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ovp-server
    name: open-volunteer-platform
  spec:
    host: ""
    to:
      kind: Service
      name: ovp-server
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Allow