---

apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: open-volunteer-platform
metadata:
  name: ovp-knative
  annotations:
    openshift.io/display-name: OVP Starter 
    description: |-
        This template allows for the deployment of the Open Volunteer Platform application on Knative.
        The OVP app contains an example Node.js server implementation that 
        connects to a MongoDB database.
        For more information, see http://openvolunteer.org/
    tags: sync, mobile, nodejs
    iconClass: icon-nodejs
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/documentation-url: https://access.redhat.com/documentation/en-us/red_hat_managed_integration/1/html-single/developing_a_data_sync_app/index
    openshift.io/support-url: https://access.redhat.com
    template.openshift.io/bindable: 'false'
    aerogear.org/datasync-template-version: '0.9.3' # TODO needs changing?
objects:

- apiVersion: serving.knative.dev/v1
  kind: Service
  metadata:
    name: open-volunteer-platform
  spec:
    template:
      spec:
        volumes:
          - name: keycloak-server
            configMap:
              name: keycloak-config
              items:
              - key: "server"
                path: "keycloak.json"
          - name: keycloak-client
            configMap:
              name: keycloak-config
              items:
              - key: "client"
                path: "keycloak.json"
          - name: keycloak-admin
            configMap:
              name: keycloak-config
              items:
              - key: "admin"
                path: "keycloak.json"               
        containers:
        - env:
            - name: MONGO_CONNECTION
              value: "${MONGO_CONNECTION}"
            - name: MONGO_COLLECTION
              value: "${MONGO_COLLECTION}" 
            - name: KAFKA_HOST
              value: "${KAFKA_HOST}"
            - name: KAFKA_PORT
              value: "${KAFKA_PORT}" 
            - name: SERVERLESS_URL
              value: "${SERVERLESS_URL}"    
            - name: NODE_ENV
              value: development # To activate playground for demo   
          image: quay.io/graphql/ovp-debezium # TODO change image name
          volumeMounts:
            - name: keycloak-server
              mountPath: "/usr/src/app/config/keycloak.json"
              readOnly: false
              subPath: keycloak.json
            - name: keycloak-admin
              mountPath: "/usr/src/admin/keycloak.json"
              subPath: keycloak.json
              readOnly: false
            - name: keycloak-client
              mountPath: "/usr/src/website/keycloak.json"
              subPath: keycloak.json
              readOnly: false   
parameters:
  - name: MONGO_COLLECTION
    displayName: "MongoDB database name"
    description: "Database name that will be used."
    value: showcase
    
  - name: MONGO_CONNECTION
    displayName: "MongoDB Connection String"
    description: "MongoDB Connection String."
    value: mongodb://user:password@mongodb/showcase
    required: true
    
  - name: KAFKA_HOST
    displayName: "Kafka host"
    description: "Kafka host that the service will connect to."
    value: kafka
    
  - name: KAFKA_PORT
    displayName: "Kafka port"
    description: "Kafka port that Kafka connection will be establised."
    value: "9092"
 
  - name: SERVERLESS_URL
    displayName: "Url that will serve the list of daily actions plans from"
    description: "Url that will serve the list of daily actions plans from."
    required: true   